---
# tasks file for roles/installpackages
- name: add apt key
  apt_key:
    url: "{{ url }}"
    state: present
  when: url != ""

- name: add respository
  apt_repository:
    repo: "{{ repo }}"
    state: present
    filename: "{{ package }}.list"
  when: repo != ""

- name: install
  apt:
    name: "{{ package }}"
    state: latest
    update_cache: yes

- name: start and enable
  service:
    name: "{{ service }}"
    state: started
    enabled: yes
